### ISSUE TITLE
Capture seed generation script

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#204]
Copy the script in [this PR](https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/350/files) so that it is runnable. Might be worth adding a tqdm progress bar while we're at it.

**Comment by Mr0grog** [comment]
If you think it belongs here, I think we should just do that instead of adding it to the DB. My thinking for putting it there instead (and in a doc, rather than a script) was that I’m not sure we *want* a script that we can just run repeatedly:

- the seed data shouldn’t need to updated very often (it needed an update in this case not because it needed an update but because it was a poor data set to begin with) and

- by the time we want to generate new data again, the script will probably need to change anyhow (for example, this script changed the format of the seed data from what we had before because we now have tags and maintainers instead of sites and agencies)

I figured it made more sense as an advisory example than an actual tool. But I’m totally fine moving it if you think it fits better here. I’d mostly like to avoid duplicating it and having multiple places where people will find it that can become out-of-sync.

**Comment by Mr0grog** [comment]
An alternative, similar approach here might be to make it an Jupyter notebook instead of a script. If that’s better, someone else should lead on that because I still find the process of reading and running those to be super obtuse.

**Comment by danielballan** [comment]
I think a Markdown snippet is fine: let the user decide whether to run that in a notebook, some IDE, or a plain script. I'd like to leave this issue open as a reminder to look at the patterns in that example and at least consider adding something similar to our Sphinx documentation, but I don't disagree with your points above.
