### ISSUE TITLE
Scanner showing double content, rendering it as new

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring-processing#230]
On a handful of pages in DOE EERE (www.energy.gov/eere), Scanner (or perhaps the Versionista file Scanner picks up -- I have not checked Versionista) shows double content on a page and renders the second set of content as new (e.g. the page has three paragraphs. These three paragraphs will show with no deletion or alteration on the previous version of the page. On the new version of the page, there will be a set of these three paragraphs with no highlighting. Following that, there will be a second set of these three paragraphs, highlighted green as new content). Going to the web page itself, it only shows a single set of content. 

## Expected Behavior
A second set of content would not appear.

## Current Behavior
Scanner is picking up (or producing? or picking up an error from Versionista) a second set of identical content on _some_ pages (and I haven't detected a pattern yet) in www.energy.gov/eere, rendering it as new. On the browser version of the web page itself, only a single set of content appears.

## Possible Solution
Dan Allan thought that there might be underlying code for a browser version and a mobile version; i'm not sure what a solution might be though. :-/ 

## Steps to Reproduce (for bugs)
1. Example: https://monitoring.envirodatagov.org/page/725cde1a-e550-49d9-b8e6-a18d40262978/21b32151-e55e-4fa7-8475-c3ed49aa01e6..796019a9-ace8-402f-bd0d-cbf2fa4565bd 
2. web page url: https://www.energy.gov/eere/solar/articles/solar-energy-technology-basics

I can find more examples if you'd like (I didn't keep a record of the pages I saw this on, but can find them again if it'd be helpful). 

## Context
It's not super high priority -- it takes some time to look through the page and realize that it is double content, and would be much better if it didn't appear as a new version -- but it's also not the end of the world. :) 

## Your Environment
Windows 10, Google Chrome version 67.0.3396.99

**Comment by danielballan** [comment]
Thanks for the thorough report, @gretchengehrke.

**Comment by Mr0grog** [comment]
Welp, looked into this, and there’s nothing even slightly funny happening at all — the page just simply has the content twice. It only shows up on this one capture (it’s not doubled up on the previous or subsequent captures).

Looking at the source code, the two copies *are* marked up differently, but not in a way that looks like one would be hidden while the other is shown. I’d bet what happened here is that a developer working on their templating system accidentally caused a summary field (probably meant for pages that list posts sequentially, like a blog — this page is short enough it could all fit in a short summary field) to be printed on the actual main article page (where a summary wouldn’t make sense). Since it is probably template related, it wouldn’t be weird to see something similar show up on a several other EERE pages.

I’m not sure there’s anything for us to fix; it looks like EERE literally just had doubled up content on their pages for a day, so we are showing exactly what we should :P
