### ISSUE TITLE
Support ETag headers

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#264]
Split off from #256, where @Mr0grog suggested:

>  Support ETag headers (maybe a hash of path + query + version?)

This seems straightforward enough. Is this is as simple as, for example

```py
hashlib.sha256(web_monitoring.__version__ + path + str(query_params)).hexdigest()
```

?

**Comment by Mr0grog** [comment]
Yep, exactly.

From the client side, it’s just an opaque string — the idea is that a client can send it as a header if it has a cached value it thinks might be stale, and the server is smart enough to know how to interpret it and determine if it indicates a fresh value. It can avoid doing all the processing it normally would if the ETag is still fresh (it just returns a 304 Not Modified status with an empty body) or do all the work and return a real result otherwise.
