### ISSUE TITLE
Towards an algorithm for Prioritization

### ISSUE THREAD

**Issue by ChaiBapchya** [edgi-govdata-archiving/web-monitoring-processing#28]
# Introduction
Based on the prima facie understanding of Domain of Environmental science,
would like to propose a mathematical model of sorts (more of a concept) that would possibly help us to develop an algorithm for Prioritizing of Meaningful changes.

# Gist
Priority will be given on the basis of Ratings and Confidence/Trust 

## Rating 
> **Value given to the word (and progressively to the sentence and the page) on the basis of Domain knowledge**

For eg - After intense study, analysts deduce/come up with following - 

Words | Rating | Type
--- | --- | ---
a,an,the | 0.0 | stopwords
tom,dick,harry | 0.0 | lay man
amazing,beautiful,destructive,fatal,life-saving,unique | 0.3 | adjectives
small,big,less,more,grand,tiny | 0.4 | variables
rain,water,wind,humidity,cyclone,tornado,flood,hurricane,summer,snow,fog | 0.5 | generic natural phenomenon
donald j trump,barack obama, ben barnanke | 0.7 | important personalities
mm,cm,hours,days,seconds | 0.8 | Units of measurement
high,low,up,down,left,right,north,east,west,south,south-east,south-west,north-east,north-west | 0.8 | directions
50%,90%,10% | 0.9 | quantifiers / numbers
carbon-di-oxide,carbon-monoxide,ozone,ethane,methane,sulfur,sulfuric acid, sulfurous acid, carbonates, sulfates, epoxy | 1 | chemical compounds

## Confidence
**The notion of confidence is the factor that is updated over time, that represents trust and accuracy of a particular rated word.**

- By that I mean, over the course of time, every Website, every change would be documented and carefully curated.
- This would enable us to gauge confidence for that particular change from a specific website.
E.g. If it is found, website X always produces changes of rating 0.2 - 0.6 can be given lower confidence (say 40%)
On the contrary, another website Y consistently provides changes of rating 1 - can be given higher confidence (say 75%)

# Priority Calculation

By basic logic,
```
updation_value = (rating) * (confidence)
```
**(Positive sentiment)**
```
Priority_new = Priority_old + updation_value
```
**(Negative sentiment)**
```
Priority_new = Priority_old - updation_value
```
After assigning priorities to every change, sort them in descending order (with highest  value first, so on and so forth)

## Deduction
Higher the priority value, more the priority assigned (important change)
Inverse, Lower the priority value, less the priority assigned (negligible change)

I would like to document this entire process if found worthy and add this to our repository.
@b5 @danielballan @dcwalk 

Note - All these values are just for namesake. They are subject to analyst and peer review.

**Comment by danielballan** [comment]
Thanks for this thorough write-up of your ideas. It's exciting to muse on how automated prioritization could work; it's one of the aspects that everyone is eager to reach. I think it will be easier to develop this discussion once we have a basic deployment up and access to many more annotated examples that illustrate the specific challenges.

**Comment by ChaiBapchya** [comment]
Yup true. But from what you know and have gone through so far, what do you make of this? any suggestions and changes? Thank you @danielballan

**Comment by danielballan** [comment]
It looks reasonable to me. I don't think I can offer more specific or constructive feedback until we are further along. The context in which a word is used will matter a lot: for example, was an item removed for unscientific reasons or was it removed because it was part of an out-of-date news article? It's a subtle distinction that requires more experience and research before we can develop an automated solution.

**Comment by janakrajchadha** [comment]
@ChaiBapchya - Pardon me if I didn't understand this correctly, but does "Negative sentiment" mean an insignificant change or an actual negative sentiment?
The priority should only be reduced if the change is insignificant, a negative sentiment should (according to my understanding) go higher up in the priority list.

**Comment by mhucka** [comment]
My apologies for my late involvement.  After reading the comments above and thinking and researching this topic a little bit, here are my thoughts. I hope this doesn't come off as too critical; it's not meant to be.  Each point below is numbered so that discussions can refer back to them more easily.  Finally, at the end, I discuss some research in revision history analysis that may be worth looking into.

First, some specific feedback about the proposal at the beginning of this page:

P1) As @danielballan also mentioned, the lack of specific case examples right now is an impediment to developing a detailed solution at this stage.  This is particularly true because we don't know (or at least I don't know) the exact form of the input to the algorithm.  So we should try to clarify the nature of the input as much as possible.  (Maybe this information is out there and I just don't know it yet -- my apologies if so!)  In the absence of this, it may be useful to think slightly more abstractly, about the sorts of things that can happen anytime one tries to evaluate changes in sets of documents.

P2) While the rating example given early on this page is interesting, I think it's impossible to assign specific numerical values right now.  (I'm specifically looking at the "rating" column in the table near the top of this page and the values 0-1.)  I am not sure we can even come up with specific words to watch for at this stage, either.  However, the general concept of detecting classes of words might be useful and might still play a role.

P3) Worth keeping in mind is that when changes occur between two versions of some document, there can be both deletions and additions.  So, something that might have to play a role in the calculation is the direction of the changes.  It might be desirable to rank deletions of some terms higher than deletions of others, and similarly, rank addition of some terms higher than addition of others, and finally, the same terms might be ranked differentially depending on whether they're deleted versus when they're added.  For instance, we might want to rank deletion of the phrase "climate change" higher than the addition of the same phrase, because deletion may imply censorship.

P4) Quantity of change may be another variable that enters into the calculations, but it has to be done carefully.  A small change may not be as significant as a large change; very small changes may represent simple edits.  The amount could be accounted for using a scaling function of some sort.  The danger here is that the small change could actually be extremely important: imagine inserting or deleting the word "not" in a sentence -- it changes the meaning completely.  So here I think what's needed is to have a list of specific words, probably hand-picked, that are given higher weight than others.

P5) It might also be important to use a subset of page differences, depending on the area of the page where the changes appeared.  For instance, some web pages have a section of the page with a list of "recent articles", and those sections change relatively frequently (e.g., every week or every month or whatever) but are meaningless from the standpoint of important changes to the page content.  I hope that the nature of the input to the algorithm will make it possible to detect regions like that, but it may not.  Still, it's worth keeping this in the back of our minds.

P6) I think the generalization of @ChaiBapchya's proposed approach is what's called Named Entity Recognition (NER).  My sense is that many NER methods are geared towards looking for specific things, and we really have no way to create a finite list of specific things to look for, so this approach alone may not be sufficient.  Still, it might be useful as an early exercise to try an NER method, in particular because some methods use only pattern-matching and don't need training data.  Also, a lot of times, what can be done is to combine multiple methods, so NER might still play a role.  The [NER page from LingPipe](http://alias-i.com/lingpipe/demos/tutorial/ne/read-me.html) is about a specific piece of software (and I'm not advocating using that in particular) but it has a pretty good list of different NER tricks.  The [NLTK book chapter on NER](http://www.nltk.org/book/ch07.html) is another page with a detailed description of NER in a different toolkit.

Aside from all that, I tried to look for relevant work on evaluating changes in documents.  This led to the discovery of work in topics that go by the names of "revision history analysis" and "controversy detection".  This is similar to the problem we're facing here; the main difference is that the research seems to be focused on edit histories of things like Wikipedia pages in order to detect controversies, so the exact methods may not be usable.  However, they may provide ideas and inspirations.  The two most relevant papers I've found so far are the following – I confess I have only skimmed them, but hopefully I didn't misunderstand them completely:

* [Using the Past To Score the Present: Extending Term Weighting Models Through Revision History Analysis](https://gist.github.com/mhucka/989b72cd6efd59afeededb2c5e638fef)

* [Improving Automated Controversy Detection on the Web](https://gist.github.com/mhucka/a8099f27eba86ad62b8c6c43252cfa56)

(To download copies of the PDFs, click the "Raw" button in the gist page.)

I hope this helps!

**Comment by ChaiBapchya** [comment]
@mhucka 
1. In my opinion, input is nothing but diff (it might seem crude or too simple. But I guess to start off constructing something, diff would be it)
2. The reason behind assigning values is to quantify them (to be able to prioritize coz without that its difficult). 3rd column "Type" is somewhat close to what you refer as "class". Yes, I concur with you - it does have an important role to play
3. Really critical point I seemed to have overlooked.
**Ranking deletions and additions.**
Point well made. But, yes how do we rank those - subject to further deliberation
4. Ya, so such words can be given rating 1.0 (highest) coz they are caution words
6. I agree NER isn't conclusive alone and needs to be coupled with more tools to serve our purpose.

Thanks for the feedback and worthwhile points.

**Comment by titaniumbones** [comment]
coming in late here, and perhaps not reading carefully enough, but should we not imagine that most of the time we will start with Boolean or at best decimal ranking of **diffs**, not words (because this is how analysts are currently collecting data)?  Are we meant to derive the word priorities statistically from the diff database? Or would we need to ask our analysts/experts to rank words manually?

**Comment by ChaiBapchya** [comment]
My logic was
It's difficult to rate diffs directly. So primarily the way this goes is
Words -> Sentences -> Diffs
Extracting important sentences from Diff and further drilling it down to words.
Then rating them and bubbling it over to diffs once again.

I wasn't aware of the current process hence didn't think in other direction. @titaniumbones

**Comment by mhucka** [comment]
@titaniumbones Those are great questions.

I think it's going to be hard to get the analysts to sit down and rank words in the abstract; I think they would need to do it in the context of actual diffs.  I like your idea of just trying the simplest thing, which is treat them as binary (present vs not present). It might be feasible to ask the experts to take samples of diffs and identify particular things they look for. Even if they can't rank their importance, just knowing "this is irrelevant" versus "this is notable" might be useful.

With respect to diffs versus words, since diffs are largely collections of words, it's probably not _unreasonable_ to base a detector/evaluator on words, but I think it's not sufficient. Still, as a first pass, one might learn something by trying a very simple word-based system.  An exercise like that is often very illuminating. Just off the top of my head, the features in a first-pass exercise could be a combination of size of diffs, direction of changes, and the presence or absence of particularly salient words in the diffs themselves.  I think such a scheme won't be very accurate, but I think it's also hard to predict exactly _why_ and _how_ it won't be sufficient.

The hardest problem is going to be getting enough training examples for an ML system....

**Comment by janakrajchadha** [comment]
@mhucka The features you've suggested for a first-pass exercise may lead us to completely unexpected results. Even if the results are not sufficient, they might point us in the right direction or to be precise "a better direction". 

It won't be difficult to accumulate sufficient training examples for the irrelevant changes as these will be the majority of all changes. I think we'll have to spend a considerable amount of time on the examples for important changes.

@titaniumbones Correct me if I'm wrong here, but as the word priorities in the diff database will be the result of an initial ranking by the experts and further review, it will be better if we derive word priorities from the database.

**Comment by daas-ankur-shukla** [comment]
wonderful thread. thanks @mhucka for directing me here
