### ISSUE TITLE
Discuss splitting differs.py into multiple modules

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#63]
Following up on @Mr0grog's comment on #59, I generally prefer one ~100-line module to several ~10-line modules, but I'm open for discussion. All of the "public" functions in `differs.py` are differs; all of the "primary" functions (whose name begins with an underscore) are utilities used by one or more differs.

**Comment by janakrajchadha** [comment]
I can't think of situations where functions will go over 20-25 lines each. I think we should let them be in a single module for now. Also, if and when we think a single file is getting too big to handle them all, maybe we can make groups based on some criteria and divide the functions into them.

**Comment by Mr0grog** [comment]
(Augh sorry for taking so long to post when this discussion was started by my comments!)

First, I’d like to say that I was not necessarily suggesting one file per differ (though that does make it simple and clear). I was more trying to get at: we should probably have a directory for differs and we could probably split our current implementation into more than one module.

I’d normally agree that one ~100 line module is better than several 10 liners, but my concerns here are two-fold:

1. The intention here is for others to add and contribute new diffing tools. Because this is a community project and not the work of a close-knit team working in the same room together, it’s really helpful to have an organizational system that supports that clearly and easily so someone knows where to put their stuff. e.g. in [this comment](https://github.com/edgi-govdata-archiving/web-monitoring/issues/36#issuecomment-314532247) I didn’t have a clear and simple way to describe where @neiljp should put his diff logic.

2. I think that most of our more interesting differs will be a fair bit more complicated than ~10 lines. It would be lovely to actually see some of @neiljp’s work soon, but I presume it’s going to be a fair bit more complex.

  I’m skeptical that our current implications are a good indicator of size, anyway, since I think they are missing a few useful special cases I can already identify (e.g. visible text should replace an image element with its `alt` text; should `title` attributes be considered somehow; should an `a` tag’s `href` be included [since this is something analysts do try to look at]?) and almost certainly plenty more none of us have thought of yet.

**Comment by Mr0grog** [comment]
> I think that most of our more interesting differs will be a fair bit more complicated than ~10 lines.

Case in point: #78

**Comment by janakrajchadha** [comment]
@Mr0grog I understand and share your concerns here. 
While creating one file per differ will definitely make it simple, it may not make sense for some differs.
For example : I think it makes sense to keep [`compute_dmp_diff`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/f7ebb517fbbbdb31f6a2f60180f0bfb554b62ab5/web_monitoring/differs.py#L60) and the two functions using it in one file. 
This may become a complex task as we add more differs but we can probably do it for the cases where we think it is obvious that we should club these together.
This is just a suggestion and we'll obviously have to see if it makes sense as the no. of differs increase.

**Comment by Mr0grog** [comment]
I want to reiterate again that **I am not saying we should have one file per differ.** My point here is that we should have an *obvious place for people contributing new differs to put their work.*

That *could* be one file per differ. But here are some other approaches that would serve the same goal:

```
web_monitoring
├─┬ differs
│ ├── basic.py (same as differs.py now)
│ └── PUT_YER_DIFF_MODULE_HERE.txt
│
├── cli.py
├── utils.py
└── etcetera.py
```

```
web_monitoring
├─┬ differs
│ ├── summary.py (differs like length, identical bytes, etc.)
│ ├── textual.py (Diff-Match-Patch-like differs)
│ ├── something_else.py
│ └── and_so_on.py
│
├── cli.py
├── utils.py
└── etcetera.py
```

**Comment by janakrajchadha** [comment]
These seem like some good ways to do it.
I think the second one is quite similar to what I had in mind.

**Comment by Mr0grog** [comment]
I’m going to go ahead and close this. Some of the reorganization we’ve done in #206 gets at what was discussed here, plus `html_diff_render` and `links_diff` are already separate. We’ll probably go farther on that naturally, so there’s probably not a need to keep this open as an explicit issue.
