### ISSUE TITLE
Fix tests and CI builds

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-processing#74]
Tests appear to be broken right now, which makes them not-super-useful. Working tests would be pretty helpful in verifying PRs like #68. This also prevents CI from being helpful.

Further, the CircleCI test script doesn’t work right now. It looks like that’s just because `coverage` is not listed in `test-requirements.txt`, but we should make sure there aren’t any other issues, either.

**Comment by janakrajchadha** [comment]
I just checked the test file and realised there are no tests for the PageFreezer differ. I'm not sure why.
After the blunders I made because of unsaved changes and missing testing, I definitely think this is really important!
This will also eliminate the trouble of reviewing a PR like you had to do for #68 😅

**Comment by janakrajchadha** [comment]
@Mr0grog I've fixed the issues I was facing while running tests for #68. The circle CI build was successful.
However, I have some other concerns which I've mentioned in the PR conversation.

**Comment by Mr0grog** [comment]
Fixed in 0e08d34637be121e93872a0d7a8d522f597e1bfa (part of #68).
