### ISSUE TITLE
Rewrite links on the way out to point to archived resources

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#96]

**Comment by Mr0grog** [comment]
Is “new tab” where we landed on this? I think there was also some back-and-forth over whether they should be simply pointing to a new tab or whether the URLs should also be rewritten to point to:

- The archive.org memento version of the URL (i.e. `http://web.archive.org/web/{timestamp}/{url}`) or
- If we are tracking the destination URL, the closest-in-time version in our UI

Also worth noting: another approach that would handle this (as well as subresource loading issues) I had briefly explored over on DB was service workers: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/91#issuecomment-329330631

That’s much more feasible than I had thought it would be when I wrote that now that I’ve realized we have to proxy all this stuff anyway (because browsers won’t load `http` resources when all our content loads over `https` in production).

**Comment by danielballan** [comment]
These are separate issues (and I neglected to create an issue for the more difficult one). I think we still want links to open in a separate tab, but the discussion muddied the two for awhile, so I'm not 100% sure where we landed.

**Comment by weatherpattern** [comment]
Moving this to v0.1.
As discussed with @danielballan this issue is a larger piece of work and not required for the initial v0.0.4 version.

**Comment by Mr0grog** [comment]
This is still important to tackle.

**Comment by Mr0grog** [comment]
For now, I think this work should happen in UI, since that is where we are doing other kinds of link and resource manipulation. See https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/382.
