### ISSUE TITLE
Broken diff example

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-processing#99]
This link text seems to be inaccurate and points to some larger problems with the side-by-sida diff view. We need to revisit our options and do much more testing.

https://monitoring-staging.envirodatagov.org/page/515db73c-920a-4663-9896-62431a0574d9/9d4de183-a186-456c-bffb-55d82989877d..775a8b04-9bac-4d0d-8db0-a8e133c4a964

**Comment by weatherpattern** [comment]
@danielballan 
I think it is rendering better and accurately now.
https://monitoring-staging.envirodatagov.org/page/515db73c-920a-4663-9896-62431a0574d9/a3840b0c-31a5-4431-8a1b-378de7b652aa..d2414ad8-eae4-448b-bfd2-e46ea7dd3428

Notes:
1.  The energy.gov website has been changed since our last capture. To compare the right-side, use this link. Appears to have all the content, and the formatting is much clearer. Our captures before Nov 2 render incorrectly in the way described in the OP. 
https://web.archive.org/web/20171219234516/https://www.energy.gov/

2. Our capture before Nov 2, don't render correctly, neither does verisonista's. Could this be due to some new libraries?

3. FYI the internet archive has a capture before Nov 2, which renders correctly:
https://web.archive.org/web/20171101142516/https://energy.gov/

**Comment by Mr0grog** [comment]
> Our capture before Nov 2, don't render correctly, neither does verisonista's. Could this be due to some new libraries?

I think this is conflating two issues of “correctness.”

1. Were the segments highlighted actually removed/added? Are the highlights in the right spot? Are links that are highlighted (or partially highlighted) pointing to a correct URL? Did the highlighting *itself* break the layout? (see 2) etc.

2. Do we have correct styling/scripting/images/etc. from the same time period as the version and can we use them instead of the URLs that were actually in the version when rendering? (Versionista does not capture these, which is why neither they nor us render pages before Nov 2 correctly. IA does capture page resources.)

I *believe* the original post here was about (1), but would need @danielballan to confirm since it’s light on details.

For (2), this is not something we can perfectly solve, since Versionista does not store page resources. We’ve talked about potentially re-writing all the resource URLs in a diff to archive.org URLs from a nearby time, but that will still be imperfect for Versionista data because we have no guarantee IA captured those resources at a time remotely close to when Versionista may have.

**Comment by weatherpattern** [comment]
This is definitely about (1). 
I looked in the Wayback Machine and compared pages from Sept 28 and Sept 29 in @danielballan 's original post. Both pages in our UI are showing all the content. Sept 28 (left side) is showing the removed Energy News items and Sept 29 (right side) the added Energy News items.

@danielballan  Did you have another concern behind this issue?


As for (2), staging renders really well now. However, my criteria in testing the UI remains to be: Would an analyst be able to identify a change? As long as additions and removals are highlighted and visiable, I'm good.

**Comment by danielballan** [comment]
Yes, this was about (1). Apologies for the light-on-details brain dump that was this issue.

> As for (2), staging renders really well now. However, my criteria in testing the UI remains to be: Would an analyst be able to identify a change? As long as additions and removals are highlighted and visiable, I'm good.

I think "staging renders really well now" is more about (1) but I guess you could say it depends on both. To be clear, we aren't event attempting to address (2) for Versionista-sourced Versions. If external resources like images or stylesheets change in place (i.e. same URL, new content) or are removed entirely, the view in the UI will become incorrect and/or degraded. As @Mr0grog outlined, we could mitigate that but there is no way to fix it perfectly in all cases.
